#app1.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
#  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          # Your workflow will overwrite this with the new ECR tag
          image: 767398149585.dkr.ecr.us-east-1.amazonaws.com/docker-repo:b485ae8
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: app1
  #template:
  #spec:
  #containers: []

  template:
    spec:
      containers: []
# template:
#   spec:
#    containers: []
